services:
  - type: web
    name: dev-web-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    # This is the correct way to override the command for PRs
    previews:
      startCommand: npm run dev
    envVars:
      - fromGroup: preview
      - key: APP_MODE
        previewValue: dev
