# useless 
services:
  - type: web
    name: dev-web-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - fromGroup: preview
      - key: APP_MODE
        value: production
        previewValue: dev
