name: Login Flow Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login-flow-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run : npm run start &
      - run : npm wait-on ${{ vars.BASE_URL }}
      - run: node tests/login.test.js
        env:
          BASE_URL: ${{vars.BASE_URL}}
          API_VERSION : ${{ vars.API_VERSION}}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}